// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaj2CvxEyPRrjS97JlAff2DhOnJRsgQX8',
    appId: '1:521964153236:web:e0bafce4898dd1e15f8781',
    messagingSenderId: '521964153236',
    projectId: 'tap-log-56fdc',
    authDomain: 'tap-log-56fdc.firebaseapp.com',
    storageBucket: 'tap-log-56fdc.firebasestorage.app',
    measurementId: 'G-7TED37PJVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdsRLKZGk7-zDQoTJJlgPpfK8M5jprGRI',
    appId: '1:521964153236:android:73bd4b7ba51beb065f8781',
    messagingSenderId: '521964153236',
    projectId: 'tap-log-56fdc',
    storageBucket: 'tap-log-56fdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0-T8JT-vMe58UnFkYIcABFJeDvdX6_aQ',
    appId: '1:521964153236:ios:18d143c342792c3e5f8781',
    messagingSenderId: '521964153236',
    projectId: 'tap-log-56fdc',
    storageBucket: 'tap-log-56fdc.firebasestorage.app',
    iosBundleId: 'com.example.tapLogMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0-T8JT-vMe58UnFkYIcABFJeDvdX6_aQ',
    appId: '1:521964153236:ios:18d143c342792c3e5f8781',
    messagingSenderId: '521964153236',
    projectId: 'tap-log-56fdc',
    storageBucket: 'tap-log-56fdc.firebasestorage.app',
    iosBundleId: 'com.example.tapLogMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaj2CvxEyPRrjS97JlAff2DhOnJRsgQX8',
    appId: '1:521964153236:web:a7ec76929520aca15f8781',
    messagingSenderId: '521964153236',
    projectId: 'tap-log-56fdc',
    authDomain: 'tap-log-56fdc.firebaseapp.com',
    storageBucket: 'tap-log-56fdc.firebasestorage.app',
    measurementId: 'G-ENH8MBFQ0W',
  );
}
